### ISSUE TITLE
Game is crashing upon doing ape atoll course

### ISSUE THREAD

**Issue by Ventus09** [geheur/weapon-animation-replacer#32]
I am unsure if this is only for ape atoll course but when I have my full graceful transmogged and I do the ape atoll course my game will freeze and either prompt a connection lost picture then either log me out entirely or just continue and let me move. If it will let me move not even 2 steps later I will freeze again and procceed to get logged out. I checked my runelite logs and it seems it is getting a NullPointer error. I turned off the plugin and I am having no issues now. I will paste the error I get in my logs to assist with solving this problem: 

2023-03-09 19:53:14 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at com.weaponanimationreplacer.WeaponAnimationReplacerPlugin.onGameStateChanged(WeaponAnimationReplacerPlugin.java:590)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:189)
	at client.sq(client.java:27736)
	at at.ga(at.java:1236)
	at ml.gg(ml.java:2739)
	at client.la(client.java:2587)
	at client.br(client.java:1111)
	at br.is(br.java:367)
	at br.run(br.java:346)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-09 19:53:57 [Client] ERROR client-patch - Client error: 3,11,43,23,2770,2747,0,0,0,0,0,0,0,2,55,0,0,1,-122,-58,35,-54,-50,3,0,15,0,-1,0,
java.lang.RuntimeException: 
	at gk.al(gk.java:41)
	at client.jc(client.java:7152)
	at client.gt(client.java:3022)
	at client.br(client.java:1110)
	at br.is(br.java:367)
	at br.run(br.java:346)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by geheur** [comment]
is this easy to replicate? what kind of settings do you have in the plugin?

**Comment by Ventus09** [comment]
> 
only settings i have is I changed my current graceful outfit to the adventurers outfit (t3)
all the tribrid combat capes infernal cape/masori assembler/god cape were changed to their respective max cape variants
and swift blade was changed to bone club

not sure if its easy to replicate but from the way it was going I would do like almost 100 laps then thats when things started to freeze/crash. I was doing the method where when I run out of run energy I would house tele then regen pool and hit the fairy ring rinse and repeat.

**Comment by geheur** [comment]
If this only happened after hours then I'm not sure if this is an issue with this plugin. That you haven't run into it again since turning it off doesn't necessarily mean much if it's rare. There's also a 30-second gap between the NPE and the game crash.
And I sure as hell won't do 100 laps of an agility course to find out if it happens to me XD.
You could try posting the game crash in runelite discord.
Unless you can find an easy way to replicate this I don't think I can do anything to look into it.

**Comment by Ventus09** [comment]
ok will do thanks for your quick response!
